name: 🏳 Test Push

on:
  push:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
      - 'tsup.config.ts'  
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/**'
      - '__tests__/**'
      - 'package.json'
      - 'tsup.config.ts'  

jobs:
  quality-checks:
    runs-on: ${{ matrix.os }}
    if: ${{ github.ref != 'refs/heads/main' }}
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project (TypeScript to JavaScript)
        run: pnpm build

      - name: Run Unit Tests
        run: pnpm test
