name: 🏳 Unit Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  

      - name: Setup Node.js
        uses: actions/setup-node@v4  
        with:
          node-version: 18.x 

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 'latest'

      - name: Install Dependencies
        run: pnpm install

      - name: Build Project (TypeScript to JavaScript)
        run: pnpm build

      - name: Run Unit Tests
        run: pnpm test

    # Only run if changes are made to files in src, __tests__, package.json, or tsup config
    if: |
      contains(github.event.head_commit.message, 'src/') ||
      contains(github.event.head_commit.message, '__tests__') ||
      contains(github.event.head_commit.message, 'package.json') ||
      contains(github.event.head_commit.message, 'tsup.config.ts')
